daily_reporter/config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
get 'daily-report', :to => 'report_generator#index'
post 'daily-report', :to => 'report_generator#index'
get 'generate-report', :to => 'report_generator#get_issue_list_data'

daily_reporter/app/controllers/report_generator_controller.rb
class ReportGeneratorController < ApplicationController
  unloadable


  before_filter :find_project, :authorize => :index; :get_issue_list_data
  before_filter :set_status_settings

  def index
    @project_id=params[:project_id]
    @date_range=params[:selectedDates]
    flag=request.method.eql? "GET"

    if ((!@date_range.nil? && !@date_range.empty?) || flag)

      begin

        from_date=Date.strptime(@date_range.split("-").first.strip, '%m/%d/%Y') unless flag
        till_date=Date.strptime(@date_range.split("-").last.strip, '%m/%d/%Y') unless flag
        project_created_date=@project.created_on.to_date

        from_date= flag ? Date.today - 7.day : from_date < project_created_date ? project_created_date : from_date > Date.today ? Date.today : from_date
        till_date= flag ? Date.today : till_date.nil? ? from_date : till_date < project_created_date ? project_created_date : till_date > Date.today ? Date.today : till_date
        @fixed_version=Version.find(:all, :conditions => ["project_id =?", @project.id])
        @graph_service=GraphDataGeneratorService.new(@project, from_date, till_date)
        @daily_data_hash = @graph_service.generate_todays_graph_data
        @categoryData = (from_date..till_date).to_a
        @pieData = @graph_service.generate_overall_bug_count_graph_data
        @seriesData = get_json_report_status(@daily_data_hash)
        @velocityData = get_json_report_data(@graph_service.generate_velocity_of_reduction_graph_data(@daily_data_hash))

        @openIssuesByPriorityData = get_json_report_data(@graph_service.generate_open_issues_by_priority_graph_data)
        @openIssuesForProjectModuleData = get_json_report_data(@graph_service.generate_open_issues_by_module_graph_data)

        @reworkPercentageData = @graph_service.generate_rework_percentage_graph_data
        @reworkByDev = @graph_service.generate_rework_by_dev_graph_data
        @defectsByAuthor = @graph_service.generate_closed_issues_by_dev_graph_data
        @openIssueCount = @graph_service.generate_day_wise_open_issues_data
        @start_date=from_date
        @end_date= till_date
      rescue Exception => exc
        logger.error("Logger [Error] : #{exc.message}")
        @error= "Please check the date format[mm/dd/yyyy-mm/dd/yyyy] or refer the server log file: #{exc.message}"
        @date_range = ''
      end
    end
  end

  def get_issue_list_data
    priorities_hash={"Low" => 3, "Normal" => 4, "High" => 5, "Urgent" => 6, "Immediate" => 7}
    @project_id=params[:project_id]
    @issue_data_array=Array.new
    @selected_date=Date.parse(params[:selected_date]) unless params[:selected_date].nil?
    @start_date=Date.parse(params[:start_date]) unless params[:start_date].nil?
    @end_date=Date.parse(params[:end_date]) unless params[:end_date].nil?
    @status_name=params[:status_id]
    @project_name=params[:priority_id]
    @module_name=params[:module_id]
    graph_service=GraphDataGeneratorService.new(@project, @start_date, @end_date) unless @start_date.nil?
    graph_service=GraphDataGeneratorService.new(@project, @selected_date, @selected_date+1.day) unless @selected_date.nil?
    status_id=graph_service.get_issue_status_hash[@status_name]
    priority_id=priorities_hash[@project_name]
    module_id=params[:module_id]
    @issue_list_data= graph_service.generate_issue_list_data(status_id, priority_id, module_id)
    @title_name= !@status_name.nil? ? @status_name : !@project_name.nil? ? @project_name : @module_name.nil? ? @module_name :''
    @selected_date= @selected_date.nil? ? "#{@start_date} - #{@end_date}" : @selected_date
  end

  private
  def find_project
    @project = Project.find(params[:project_id])
  end

  def set_status_settings
    IssueStatusHelper.set_status_settings
  end

  private
  def get_json_report_data(data_hash)
    aggregator=StatusDataAggregator.new
    data_hash.each_pair { |hash_name, hash_data|
      report_data=ReportData.new(hash_name)
      report_data.data=hash_data
      aggregator.status_data_list<<report_data
    }
    return aggregator.to_series_json
  end

  def get_json_report_status(report_status)
    aggregator=StatusDataAggregator.new
    @graph_service.get_issue_status_hash.each_pair { |issue_name, issue_id|
      report_data=ReportData.new(issue_name)
      report_data.data=report_status[issue_id]
      aggregator.status_data_list<<report_data
    }
    return aggregator.to_series_json
  end
end

daily_reporter/app/helpers/report_generator_helper.rb
module ReportGeneratorHelper


  def get_velocity_rate_data(new_issue_array, rework_issue_array, complete_issue_array, closed_issue_array)
    aggregator=StatusDataAggregator.new
    new_inProgress_sum = get_array_sum(new_issue_array, rework_issue_array)
    closed_complete_sum = get_array_sum(complete_issue_array, closed_issue_array)

    velocity_data=ReportData.new("Velocity")
    velocity_data.data=get_array_difference(closed_complete_sum, new_inProgress_sum)
    aggregator.status_data_list<<velocity_data

    report_data=ReportData.new("Avg-velocity")
    report_data.data=get_velocity_average_data(velocity_data.data)

    aggregator.status_data_list<<report_data
    return aggregator.to_series_json
  end

  def get_velocity_average_data(velocity_data)
    avg_velocity_array = Array.new
    avg_velocity_array[0]=velocity_data[0]
    for index in (1...velocity_data.length)
      avg_velocity_array[index] = (velocity_data[0]+velocity_data[index])/ (index + 1)
    end
    return avg_velocity_array
  end


  def get_array_sum(first_array, second_array)
    sum_array = Array.new
    for index in (0...first_array.length)
      sum_array[index] = first_array[index] + second_array[index]
    end
    return sum_array
  end

  def get_array_difference(first_array, second_array)
    diff_array = Array.new
    for index in (0...first_array.length)
      diff_array[index] = first_array[index] - second_array[index]
    end
    return diff_array
  end

  def generate_chart_data(from_date, till_date, project)
    closed_issues= IssueWrapper.get_issues_between_days(from_date, till_date, StatusWrapper::CLOSED, project.id)
    total_issues= IssueWrapper.get_total_issues(till_date + 1,project.id)
    return [['Closed', closed_issues], ['Open',total_issues - closed_issues]]
  end

  def get_issue_status_hash
    issue_status_hash={IssueStatus.find(StatusWrapper::NEW).name => StatusWrapper::NEW,
                       IssueStatus.find(StatusWrapper::CLOSED).name => StatusWrapper::CLOSED,
                       IssueStatus.find(StatusWrapper::COMPLETED).name => StatusWrapper::COMPLETED,
                       IssueStatus.find(StatusWrapper::IN_PROGRESS).name => StatusWrapper::IN_PROGRESS,
                       IssueStatus.find(StatusWrapper::REWORK).name => StatusWrapper::REWORK
    }
    return issue_status_hash
  end

  def get_open_issues_on_priority(from_date, till_date, project)
    aggregator=StatusDataAggregator.new
    total_new_issues_count=get_issues_till_date_count(from_date, StatusWrapper::NEW, project.id)
    priorities_hash={"Low" => 3, "Normal" => 4, "High" => 5, "Urgent" => 6, "Immediate" => 7}
    priorities_hash.each_pair { |priority, priority_id|
      report_data=ReportData.new(priority)
      (from_date..till_date).select {|day|
        new_issue_count = get_issue_status_count_on_day_priority(day, StatusWrapper::NEW, project.id, priority_id)
        rework_issue_count = get_issue_status_count_on_day_priority(day, StatusWrapper::REWORK, project.id, priority_id)
        inProgress_issue_count = get_issue_status_count_on_day_priority(day, StatusWrapper::IN_PROGRESS, project.id, priority_id)
        report_data.data<<(new_issue_count + rework_issue_count + inProgress_issue_count)
      }
      aggregator.status_data_list<<report_data
    }
    aggregator.to_series_json
  end

  def get_open_issues_day_wise(from_date, till_date, project)
    report_data=Array.new
    (from_date..till_date).select { |day|
      temp_date=day + 1
      total_issue_count = IssueWrapper.get_total_issues(temp_date,project.id)
      closed_issue_count = IssueWrapper.get_issues_till_date(temp_date,StatusWrapper::CLOSED,project.id)
      report_data<<(total_issue_count - closed_issue_count)
    }
    return report_data
  end


  def get_issue_status_count_on_day_priority(date, issueStatus, project_id, priority_id)
    start_date=date
    till_date=start_date+1.day
    return IssueWrapper.get_issues_between_days_by_priority(start_date, till_date, project_id, issueStatus, priority_id)
  end

  def get_open_issues_for_project_module(from_date, till_date, project)
    aggregator=StatusDataAggregator.new
    project_modules = IssueWrapper.get_project_modules(project.id)
    project_modules.each do |project_module|
      report_data=ReportData.new(project_module.name)
      (from_date..till_date).select {|day|
        new_issue_count = get_issue_status_count_on_day_for_module(day, StatusWrapper::NEW, project.id, project_module.id)
        rework_issue_count = IssueWrapper.get_issues_on_day(day, StatusWrapper::REWORK, project_module.id)
        inProgress_issue_count = IssueWrapper.get_issues_on_day(day, StatusWrapper::IN_PROGRESS, project_module.id)
        report_data.data<<(new_issue_count + rework_issue_count + inProgress_issue_count)
      }
      aggregator.status_data_list<<report_data
    end
     return aggregator.to_series_json
  end

  def get_issue_status_count_on_day_for_module(date, issueStatus, project_id, project_module_id)
    start_date=date
    till_date=start_date+1.day
    return IssueWrapper.get_issues_between_days_for_module(start_date, till_date, project_id, issueStatus, project_module_id)
  end

  def get_issues_till_date_count(date, issueStatus, project_id)
      return  IssueWrapper.get_issues_till_date(date, issueStatus, project_id)
  end

  # Returns the rework percentage
  def get_rework_percentage(from_date, till_date, project)
    # Initialize data aggregator to send data back in JSON format
    aggregator = StatusDataAggregator.new
    # Calculate Rework Percentage
    rework_percentage = ReportData.new("Rework Percentage")
    # Calculate Average Rework Percentage
    avg_rework_percentage = ReportData.new("Avg Rework Percentage")
    closed_issue_array = Array.new
    rework_issue_array = Array.new
    resolved_issue_array = Array.new
    (from_date..till_date).select { |day|
      closed_issue_array << IssueWrapper.get_issues_on_day(day, StatusWrapper::CLOSED, project.id)
      rework_issue_array << IssueWrapper.get_issues_on_day(day, StatusWrapper::REWORK, project.id)
      resolved_issue_array << IssueWrapper.get_issues_on_day(day, StatusWrapper::COMPLETED, project.id)
    }
    rework_percentage.data = compute_rework_percentage(rework_issue_array, closed_issue_array, resolved_issue_array)
    avg_rework_percentage.data = compute_rework_average(rework_percentage.data)
    aggregator.status_data_list<<rework_percentage
    aggregator.status_data_list<<avg_rework_percentage
    return aggregator.to_series_json
  end

  # Computes the rework percentage
  def compute_rework_percentage(rework_array, closed_array, completed_array)
    rework_percentage = Array.new
    if rework_array.nil? || !rework_array.respond_to?("each")
      return nil
    end
    sum_array = get_array_sum(closed_array, completed_array)
    for index in (0...rework_array.length)
      begin
        rework_percentage[index] = ((rework_array[index] * 100 )/sum_array[index])
      rescue
        rework_percentage[index] = 0
      end
    end
    return rework_percentage
  end

  # Computes the average rework percentage
  def compute_rework_average(rework_percentage)
    if rework_percentage.nil? || !rework_percentage.respond_to?("each")
      return nil
    end
    avg_rework_percentage = Array.new
    avg_rework_percentage[0] = rework_percentage[0]
    for index in (1...rework_percentage.length)
      sum_rework_percentage = 0
      x = index;
      while x > 0
        if !rework_percentage[x].nil?
          sum_rework_percentage += rework_percentage[x]
        end
        x = x - 1
      end
      avg_rework_percentage[index] = sum_rework_percentage / (index + 1)
    end
    return avg_rework_percentage
  end

  def get_rework_by_dev(start_date, end_date, project)
    role_id = 4
    return IssueWrapper.get_issue_status_by_user(start_date, end_date, project.id, StatusWrapper::NEW, role_id)
  end

  def get_closed_defects_by_author(project)
    tracker_id = 1
    return IssueWrapper.get_issues_by_author(project.id, tracker_id, StatusWrapper::COMPLETED)
  end
end

daily_reporter/app/views/report_generator/_chart.html.erb
<% content_for :header_tags do %>
    <%= javascript_include_tag "js/pieChart.js",:plugin => 'daily_reporter' %>
    <%= javascript_include_tag "js/area-chart.js", :plugin => 'daily_reporter' %>
    <%= javascript_include_tag "js/mixed-chart.js", :plugin => 'daily_reporter' %>    
    <% if request.method.eql?"POST" %>
        <%= javascript_include_tag "js/stacked-chart.js",:plugin => 'daily_reporter' %>
        <%= javascript_include_tag "js/open-issues-by-priority.js",:plugin => 'daily_reporter' %>
        <%= javascript_include_tag "js/open-issues-for-project-module.js",:plugin => 'daily_reporter' %>
        <%= javascript_include_tag "js/rework-percentage-chart.js",:plugin => 'daily_reporter' %>
    <% end %>
    <%= javascript_include_tag "js/main.js", :plugin => 'daily_reporter' %>
    <%= javascript_include_tag "js/rework-by-dev.js", :plugin => 'daily_reporter' %>
    <%= javascript_include_tag "js/defects-by-author.js", :plugin => 'daily_reporter' %>
<% end %>

<%= javascript_tag do %>
    pieTitleName = 'Bug Count Graph';
    yAxisTitleName = 'Defects';
    velocity_Title = 'Velocity of Reduction';
    mixedTitleName = 'Defect Arrival Kill rate';
    reworkByDevTitle = 'Rework By Developers'
    defectsByAuthorTitle = 'Defects for Verification'
    openIssuesForProjectModule_Title = 'Open Issues by Module/Category'

    piaChartData =  <%= @pieData.to_json.html_safe %>;
    velocityData = <%= @velocityData.html_safe %>;
    categoryData = <%= @categoryData.to_json.html_safe %> ;
    reworkByDevData = <%= @reworkByDev.to_json.html_safe %>
    defectsByAuthorData = <%= @defectsByAuthor.to_json.html_safe %>

    arrivalData = <%= @daily_data_hash[StatusWrapper::NEW].to_json.html_safe %>;
    activeData = <%= @openIssueCount.to_json.html_safe %>;
    killData = <%= @daily_data_hash[StatusWrapper::CLOSED].to_json.html_safe %>;

    <% if request.method.eql?"POST" %>
        stackedTitleName = 'Day-wise Graph';
        openIssuesByPriority_Title = 'Open Issues By Priority';
        reworkPercentageTitle = 'Rework Percentage';

        dateRange = '<%= @from_date %> To <%= @till_date %>';
        seriesData = <%= @seriesData.html_safe %>;

        openIssuesByPriority_Data = <%= @openIssuesByPriorityData.html_safe %>;

        openIssuesForProjectModule_Data = <%= @openIssuesForProjectModuleData.html_safe %>;

        reworkPercentageData = <%= @reworkPercentageData.html_safe %> ;
    <% end %>
<% end %>
<div class="chart_container">
  <div class="chartboxleft">
    <a class="drag-chart" ></a>
    <a class="resize-chart" chart="pie"></a>
    <div id="pie-container" chart_title="Total Count Graph"></div>
  </div>
  <div class="chartboxleft" >
    <a class="drag-chart" ></a>
    <a class="resize-chart" chart="mixed"></a>
    <div id="mixed-container" chart_title="Defect Arrival Kill rate"></div>
  </div>

  <div class="chartboxleft" >
    <a class="drag-chart" ></a>
    <a class="resize-chart" chart="area"></a>
    <div id="area-container" chart_title="Velocity of Reduction"></div>
  </div>
  <div class="chartboxleft">
    <a class="drag-chart" ></a>
    <a class="resize-chart" chart="pie"></a>
    <div id="rework-by-dev-container" chart_title="Rework By Developers"></div>
  </div>
  <div class="chartboxleft">
    <a class="drag-chart" ></a>
    <a class="resize-chart" chart="pie"></a>
    <div id="defects-to-verify" chart_title="Defects for Verfication"></div>
  </div>
  <% if request.method.eql?"POST" %>
  <div class="chartboxleft" >
    <a class="drag-chart" ></a>
    <a class="resize-chart" chart="stacked"></a>
    <div id="stacked-container" chart_title="Todays Update"></div>
  </div>

  <div class="chartboxleft" >
    <a class="drag-chart" ></a>
    <a class="resize-chart" chart="oibp"></a>
    <div id="open-issues-by-priority-container" chart_title="Open Issues By Priority"></div>
  </div>

  <div class="chartboxleft">
    <a class="drag-chart" ></a>
    <a class="resize-chart" chart="oifpm"></a>
    <div id="open-issues-for-project-module-container" chart_title="Open Issues For Project Module"></div>
  </div>
  <div class="chartboxleft" >
    <a class="drag-chart" ></a>
    <a class="resize-chart" chart="rework"></a>
    <div id="rework-container" chart_title="Rework Percentage"></div>
  </div>
  <%end%>
</div>

daily_reporter/app/views/report_generator/get_issue_list_data.html.erb
<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'css/chart.css', :plugin => 'daily_reporter' %>
<% end %>

  <h2><%=  @title_name %> : <%= @selected_date %></h2>
  <div>
    <div class="div-id-list"><b>Issue Id</b></div>
    <div class="div-summary-list"><b>Summary</b></div>
    <div class="div-name-list"><b>Assigned To</b></div>
    <div class="div-name-list"><b>Filed By</b></div>
  </div>
  <div>
    <% @issue_list_data.each do |issue, issue_summary, issue_assigned_to_id, issue_author_id| %>
        <div style="clear: both"></div>
        <div class="div-id-list"><%= link_to issue , issue_path(issue) %></div>
        <div class="div-summary-list"><%= issue_summary %></div>
        <div class="div-name-list"><%= issue_assigned_to_id %></div>
        <div class="div-name-list"><%= issue_author_id %></div>
    <% end %>
  </div>

daily_reporter/app/views/report_generator/index.html.erb
<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'css/ui.daterangepicker.css', :plugin => 'daily_reporter' %>
    <%= stylesheet_link_tag 'css/chart.css', :plugin => 'daily_reporter' %>
<% end %>

<% content_for :header_tags do %>
    <%= javascript_include_tag 'js/date.js', :plugin => 'daily_reporter' %>
    <%= javascript_include_tag 'js/daterangepicker.jQuery.js', :plugin => 'daily_reporter' %>
    <%= javascript_include_tag "js/highcharts.js", :plugin => 'daily_reporter' %>
    <%= javascript_include_tag "js/exporting.js", :plugin => 'daily_reporter' %>
<% end %>
<script type="text/javascript">
    $(function () {
        $('#selectedDates').daterangepicker({arrows: true});
    });
</script>
<input type="hidden" name="projectId" value="<%= @project_id%> ">
<input type="hidden" name="start_date" value="<%= @start_date %>">
<input type="hidden" name="end_date" value="<%= @end_date %>">
<div style="float: left;width: 100%;height: 50px;">
  <a class="toggle-setting rightFloat" style="margin-top: 14px;margin-left: 10px;">
    <%= image_tag("package_settings.ico", :alt => "Settings", :plugin => 'daily_reporter', :size => '20x20') %>
  </a>

  <div>

  <div class="rightFloat" style="padding-top: 7px;">
    <%= form_tag("daily-report?project_id="+@project_id, :method => "post") do %>
        <div class="rightFloat">
          <%= button_tag 'Submit', :class => "submit_button"%>
        </div>
        <div class="rightFloat" style="margin-top: 4px;height: 21px;margin-right: 6px;">
          <input type="text" value="<%= @date_range %>" id="selectedDates" name="selectedDates"/>
        </div>

    <% end %>
    <div class="rightFloat" style="margin-top: 2px;">
      <h3 style="color: #80b0da"> Select Date Range </h3>
    </div>
  </div>

</div>
  </div>
<% if !@error.nil? && !@error.empty? %>
    <h4 style="color: RED"><%= @error %></h4>
<% end %>

<div class="chart-settings">
  <div class="option_combo">
    <ul class="sort_container">

    </ul>
  </div>
</div>
<% if @error.nil? %>
    <% if @date_range.nil? %>
        <div>
          <%= render :partial => ("chart") %>
        </div>
    <% end %>
<% end %>
<div>
  <%= render :partial => ("chart") if !@date_range.nil? && !@date_range.empty? %>
</div>